<?php
return 
[
	'en' =>
	[
		'save' => 'Save',
		'cancel' => 'Cancel',
		'new' => 'New',
		'edit' => 'Edit',
		'delete' => 'Delete',
		'delete_confirmation' => 'Do you really want to delete this record?',
		'pages' => 'Pages',
		'actions' => 'Actions',
		'version' => 'Version',
		'search' => 'Search',
		'reset_search' => 'Reset search',
		'csv_export' => 'CSV Export',
		'xml_export' => 'XML Export',
		'yes' => 'Yes',
		'no' => 'No',
		'search_warning_html' => '<b>Attention!</b> Results in this view are limited by your <b>search</b>.',
		'filter_warning_html' => '<b>Attention!</b> Results in this view are limited by <b>filters</b>.',
		'prev' => 'Previous',
		'next' => 'Next',
		'first' => 'First',
		'last' => 'Last',
		'footer_html' => 'Powered by <a href="https://laravel.com/" target="_blank">Laravel</a> and <a href="https://adminlte.io/" target="_blank">AdminLTE</a>. Inspired by <a href="https://crudkit.com/" target="_blank">CRUDKit</a> and <a href="https://github.com/markpurser/laravel-crudkit" target="_blank">Laravel CRUDKit</a>.',
		'wrong_username_password' => 'Wrong username or wrong password.',
		'not_logged_in' => 'You are not logged in.',
		'no_permission' => 'You have no permisson to access this page or to perform this action.',
		//Export:
		'crudkit_csv_export' => '--- Crudkit CSV Export ---',
		'crudkit_xml_export' => '--- Crudkit XML Export ---',
		'page' => 'Page',
		'page_id' => 'Page ID',
		'date' => 'Date',
		'time' => 'Time',
		'search_term' => 'Search term',
		'restricted_by_search' => 'Restricted by Search',
		'restricted_by_filter' => 'Restricted by Filters',
		'column' => 'column',
		'operator' => 'operator',
		'value' => 'value',
		'filter' => 'Filter',
		//Chart
		'show_as_chart' => 'Show as chart',
		'save_chart' => 'Save Digram',
		'crudkit_diagram_view' =>'CRUDKit Diagram View',
		'x_axis' => 'x-Axis',
		'y_axis' => 'y-Axis',
		'aggregation' => 'Aggregation',
		'aggregation_count' => 'Record Count',
		'aggregation_sum' => 'Sum',
		'aggregation_avg' => 'Average',
		'aggregation_min' => 'Minimum',
		'aggregation_max' => 'Maximum',
		'x_axis_empty' => '(empty)',
		'filters' => 'Filters',
		'filter_value' => 'Enter filter value...',
		'startswith' => 'starts with',
		'endswith' => 'ends with',
		'contains' => 'contains',
		'load' => 'Load'
	],
	'de' =>
	[
		'save' => 'Speichern',
		'cancel' => 'Abbrechen',
		'new' => 'Neu',
		'edit' => 'Bearbeiten',
		'delete' => 'Löschen',
		'delete_confirmation' => 'Wollen sie diesen Datensatz wirklich löschen?',
		'pages' => 'Seiten',
		'actions' => 'Funktionen',
		'version' => 'Version',
		'search' => 'Suchen',
		'reset_search' => 'Suche zurücksetzen',
		'csv_export' => 'CSV Export',
		'xml_export' => 'XML Export',
		'yes' => 'Ja',
		'no' => 'Nein',
		'search_warning_html' => '<b>Achtung!</b> Die Ergebnisse dieser Ansicht sind durch die <b>Suche</b> eingeschränkt.',
		'filter_warning_html' => '<b>Achtung!</b> Die Ergebnisse dieser Ansicht sind durch <b>Filter</b> eingeschränkt.',
		'prev' => 'Zurück',
		'next' => 'Nächste',
		'first' => 'Erste',
		'last' => 'Letzte',
		'footer_html' => 'Powered by <a href="https://laravel.com/" target="_blank">Laravel</a> and <a href="https://adminlte.io/" target="_blank">AdminLTE</a>. Inspired by <a href="https://crudkit.com/" target="_blank">CRUDKit</a> and <a href="https://github.com/markpurser/laravel-crudkit" target="_blank">Laravel CRUDKit</a>.',
		'wrong_username_password' => 'Falscher Benutzername oder falsches Passwort.',
		'not_logged_in' => 'Sie sind nicht eingeloggt.',
		'no_permission' => 'Sie haben keine Berechtigung für den Zugriff auf diese Seite oder zum Durchführen der Aktion.',
		//CSV Export:
		'crudkit_csv_export' => '--- CRUDKit CSV Export ---',
		'crudkit_xml_export' => '--- Crudkit XML Export ---',
		'page' => 'Seite',
		'page_id' => 'Page ID',
		'date' => 'Datum',
		'time' => 'Uhrzeit',
		'search_term' => 'Suchbegriff',
		'restricted_by_search' => 'Einschränkung durch Suche',
		'restricted_by_filter' => 'Einschränkung durch Filter',
		'column' => 'Spalte',
		'operator' => 'Operator',
		'value' => 'Wert',
		'filter' => 'Filter',
		//Chart
		'show_as_chart' => 'Als Diagramm',
		'save_chart' => 'Digramm Speichern',
		'crudkit_diagram_view' => 'CRUDKit Diagramm Ansicht',
		'x_axis' => 'x-Achse',
		'y_axis' => 'y-Achse',
		'aggregation' => 'Aggregatfunktion',
		'aggregation_count' => 'Anzahl Datensätze',
		'aggregation_sum' => 'Summe',
		'aggregation_avg' => 'Durchschnitt',
		'aggregation_min' => 'Minimum',
		'aggregation_max' => 'Maximum',
		'x_axis_empty' => '(leer)',
		'filters' => 'Filter',
		'filter_value' => 'Filterwert eingeben...',
		'startswith' => 'beginnt mit',
		'endswith' => 'endet mit',
		'contains' => 'enthält',
		'load' => 'Laden'
	]
];